DoubleNode\[ChangelogEntry\]: {
  shape: class
}

DoubleNode\[Credentials\]: {
  shape: class
}

DoubleNode\[Equipment\]: {
  shape: class
}

DoubleNode\[InventoryItem\]: {
  shape: class
}

DoubleNode\[Request\]: {
  shape: class
}

DoubleNode\[User\]: {
  shape: class
}
