DoubleList\[ChangelogEntry\]: {
  shape: class
}

DoubleList\[Credentials\]: {
  shape: class

  +T: Credentials
}

DoubleList\[Equipment\]: {
  shape: class

  +T: Equipment
}

DoubleList\[InventoryItem\]: {
  shape: class

  +T: InventoryItem
}

DoubleList\[Request\]: {
  shape: class

  +T: Request
}

DoubleList\[User\]: {
  shape: class
}
