FileBackedList\[ChangelogEntry\]: {
  shape: class

  +T: ChangelogEntry
}

FileBackedList\[Credentials\]: {
  shape: class

  +T: Credentials
}

FileBackedList\[Equipment\]: {
  shape: class

  +T: Equipment
}

FileBackedList\[InventoryItem\]: {
  shape: class

  +T: InventoryItem
}

FileBackedList\[Request\]: {
  shape: class

  +T: Request
}

FileBackedList\[User\]: {
  shape: class

  +T: User
}
