direction: up

Changelog {
  shape: class
}

CredentialsList {
  shape: class
}

EquipmentList {
  shape: class
}

Inventory {
  shape: class
}

RequestList {
  shape: class
}

UserList {
  shape: class
}