direction: up

Date -> DateTime: extends {
  target-arrowhead {
    shape: triangle
    style.filled: false
  }
}

Time -> DateTime: extends {
  target-arrowhead {
    shape: triangle
    style.filled: false
  }
}