direction: up

Changelog -> FileBackedList\[ChangelogEntry\]: extends {
  target-arrowhead: {
    shape: triangle
    style.filled: false
  }
}

CredentialsList -> FileBackedList\[Credentials\]: extends {
  target-arrowhead: {
    shape: triangle
    style.filled: false
  }
}

EquipmentList -> FileBackedList\[Equipment\]: extends {
  target-arrowhead: {
    shape: triangle
    style.filled: false
  }
}

Inventory -> FileBackedList\[InventoryItem\]: extends {
  target-arrowhead: {
    shape: triangle
    style.filled: false
  }
}

RequestList -> FileBackedList\[Request\]: extends {
  target-arrowhead: {
    shape: triangle
    style.filled: false
  }
}

UserList -> FileBackedList\[User\]: extends {
  target-arrowhead: {
    shape: triangle
    style.filled: false
  }
}