# ...@../../classes/generics/file-backed-list\[t\]

DoubleList\[ChangelogEntry\] -> DoubleList\[T\]: specializes {
  style.stroke-dash: 3
}

DoubleList\[Credentials\] -> DoubleList\[T\]: specializes {
  style.stroke-dash: 3
}

DoubleList\[Equipment\] -> DoubleList\[T\]: specializes {
  style.stroke-dash: 3
}

DoubleList\[InventoryItem\] -> DoubleList\[T\]: specializes {
  style.stroke-dash: 3
}

DoubleList\[Request\] -> DoubleList\[T\]: specializes {
  style.stroke-dash: 3
}

DoubleList\[User\] -> DoubleList\[T\]: specializes {
  style.stroke-dash: 3
}