# ...@../../classes/generics/double-node\[t\]

DoubleNode\[ChangelogEntry\] -> DoubleNode\[T\]: specializes {
  style.stroke-dash: 3
}

DoubleNode\[Credentials\] -> DoubleNode\[T\]: specializes {
  style.stroke-dash: 3
}

DoubleNode\[Equipment\] -> DoubleNode\[T\]: specializes {
  style.stroke-dash: 3
}

DoubleNode\[InventoryItem\] -> DoubleNode\[T\]: specializes {
  style.stroke-dash: 3
}

DoubleNode\[Request\] -> DoubleNode\[T\]: specializes {
  style.stroke-dash: 3
}

DoubleNode\[User\] -> DoubleNode\[T\]: specializes {
  style.stroke-dash: 3
}