# ...@../../classes/generics/file-backed-list\[t\]

FileBackedList\[ChangelogEntry\] -> FileBackedList\[T\]: specializes {
  style.stroke-dash: 3
}

FileBackedList\[Credentials\] -> FileBackedList\[T\]: specializes {
  style.stroke-dash: 3
}

FileBackedList\[Equipment\] -> FileBackedList\[T\]: specializes {
  style.stroke-dash: 3
}

FileBackedList\[InventoryItem\] -> FileBackedList\[T\]: specializes {
  style.stroke-dash: 3
}

FileBackedList\[Request\] -> FileBackedList\[T\]: specializes {
  style.stroke-dash: 3
}

FileBackedList\[User\] -> FileBackedList\[T\]: specializes {
  style.stroke-dash: 3
}