Credentials: {
  shape: class

  -user_id\: int
  -password\: str
  -role\: Literal\["investigador", "administrador"\]

  +__init__(user_id\: int, password\: str, role\: Literal\["investigador", "administrador"\]): Credentials
  +ask(): Credentials

  from_csv(csv_string\: str): Credentials
  to_csv(): str

  get_user_id(): int
  get_password(): str
  get_role(): Literal\["investigador", "administrador"\]
  get_user(): User

  set_user_id(user_id\: int): None
  set_password(password\: str): None
  set_role(role\: Literal\["investigador", "administrador"\]): None

  is_researcher(): bool
  is_administrator(): bool
}