DateTime: {
  shape: class

  +__init__(year\: Optional\[int\], month\: Optional\[int\], day\: Optional\[int\], hour\: Optional\[int\], minute\: Optional\[int\], second\: Optional\[int\]): DateTime
  +ask(prompt\: str, error_message\: str): DateTime

  +from_csv(csv_string\: str): DateTime
  +to_csv(): str

  +get_date(): Date
  +get_time(): Time

  +set_date(date\: Date): None
  +set_time(time\: Time): None

  +now(): DateTime

  +__eq__(other\: object): bool
  +__ne__(other\: object): bool
}