Researcher: {
  shape: class

  +output_inventory(): None
  +add_equipment(): None
  +delete_equipment(): None
  +output_requests_status(file\: Union\[StringIO, TextIO\] = sys\.stdout): None
  +save_requests_status(): None
  +save_inventory(): None
  +display_menu(): None
}