direction: up

Changelog <-> ChangelogEntry: {
  source-arrowhead: {
    shape: diamond
    label: 0..*
    style.filled: false
  }

  target-arrowhead: {
    label: 0..*
  }
}

CredentialsList <-> Credentials: {
  source-arrowhead: {
    shape: diamond
    label: 0..*
    style.filled: false
  }

  target-arrowhead: {
    label: 0..*
  }
}

EquipmentList <-> Equipment: {
  source-arrowhead: {
    shape: diamond
    label: 0..*
    style.filled: false
  }

  target-arrowhead: {
    label: 0..*
  }
}

Inventory <-> InventoryItem: {
  source-arrowhead: {
    shape: diamond
    label: 0..*
    style.filled: false
  }

  target-arrowhead: {
    label: 0..*
  }
}

RequestList <-> Request: {
  source-arrowhead: {
    shape: diamond
    label: 0..*
    style.filled: false
  }

  target-arrowhead: {
    label: 0..*
  }
}

UserList <-> User: {
  source-arrowhead: {
    shape: diamond
    label: 0..*
    style.filled: false
  }

  target-arrowhead: {
    label: 0..*
  }
}