direction: up

FileBackedList\[ChangelogEntry\] <-> DoubleNode\[ChangelogEntry\]: {
  source-arrowhead: {
    shape: diamond
    label: 0..*
    style.filled: false
  }

  target-arrowhead: {
    label: 0..*
  }
}

FileBackedList\[Credentials\] <-> DoubleNode\[Credentials\]: {
  source-arrowhead: {
    shape: diamond
    label: 0..*
    style.filled: false
  }

  target-arrowhead: {
    label: 0..*
  }
}

FileBackedList\[Equipment\] <-> DoubleNode\[Equipment\]: {
  source-arrowhead: {
    shape: diamond
    label: 0..*
    style.filled: false
  }

  target-arrowhead: {
    label: 0..*
  }
}

FileBackedList\[InventoryItem\] <-> DoubleNode\[InventoryItem\]: {
  source-arrowhead: {
    shape: diamond
    label: 0..*
    style.filled: false
  }

  target-arrowhead: {
    label: 0..*
  }
}

FileBackedList\[Request\] <-> DoubleNode\[Request\]: {
  source-arrowhead: {
    shape: diamond
    label: 0..*
    style.filled: false
  }

  target-arrowhead: {
    label: 0..*
  }
}

FileBackedList\[User\] <-> DoubleNode\[User\]: {
  source-arrowhead: {
    shape: diamond
    label: 0..*
    style.filled: false
  }

  target-arrowhead: {
    label: 0..*
  }
}