...@../../interfaces/csv-serializable

ChangelogEntry -> CSVSerializable: implements {
  style.stroke-dash: 3
}

Credentials -> CSVSerializable: implements {
  style.stroke-dash: 3
}

Equipment -> CSVSerializable: implements {
  style.stroke-dash: 3
}

InventoryItem -> CSVSerializable: implements {
  style.stroke-dash: 3
}

Request -> CSVSerializable: implements {
  style.stroke-dash: 3
}

User -> CSVSerializable: implements {
  style.stroke-dash: 3
}