direction: up

Session <-> Session\.Current: {
  source-arrowhead: {
    shape: diamond
    label: 1
    style.filled: true
  }

  target-arrowhead: {
    label: 1
  }
}

Session <-> Session\.Shared: {
  source-arrowhead: {
    shape: diamond
    label: 1
    style.filled: true
  }

  target-arrowhead: {
    label: 1
  }
}